
BLENDER="C:\Program Files\Blender Foundation\Blender 4.5\blender.exe"
DIST=../dist

all : \
    $(DIST)/game3_1.pnct \
    $(DIST)/game3_1.scene \

$(DIST)/game3_1.scene : game3_1.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "game3_1.blend:Main" "$(DIST)/game3_1.scene"

$(DIST)/game3_1.pnct : game3_1.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "game3_1.blend:Main" "$(DIST)/game3_1.pnct" 
